// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  'aws_project_region': 'eu-west-1',
  'aws_cognito_identity_pool_id': 'eu-west-1:76fc2278-d8cc-4503-a68d-40c8d65f296f',
  'aws_cognito_region': 'eu-west-1',
  'aws_user_pools_id': 'eu-west-1_XWG61pKdq',
  'aws_user_pools_web_client_id': '4rb11et8vmvd8n9al4jppft0bj',
  'oauth': {
    'domain': 'auth.simplestubs.com',
    'scope': ['email'],
    'redirectSignIn': 'https://localhost:8080/callback/',
    'redirectSignOut': 'https://localhost:8080/',
    'responseType': 'code'
  },
  'cookieStorage': {
    'domain': 'localhost',
    'path': '/',
    'expires': 1,
    'secure': false
  },
  'federationTarget': 'COGNITO_USER_POOLS',
  'aws_appsync_graphqlEndpoint': 'https://unqcpvdgerce5hh7am5sqvat6q.appsync-api.eu-west-1.amazonaws.com/graphql',
  'aws_appsync_region': 'eu-west-1',
  'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS',
  'bucket': 'simplestubs',
  'region': 'eu-west-1'
}

export default awsmobile
